### ISSUE TITLE
2017 Cycle 3 Release

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#1]
Here are the major release goals for 2017 Cycle 3 at XPD. This epic will link to issues across the org that need to be addressed before the release.

## Major Goals
- Advanced Shutter Protocol
- Data Reduction and Visualization Pipeline
- New Schema/Beamline Long Term Configuration

### Data Reduction and Visualization Pipeline
1. Beamline staff starts beamtime on controls computer
1. Beamline staff runs proxy script on visualization computer
1. Beamline staff runs analysis script on visualization computer (potentially with CLI args/kwargs)
1. User starts experiment with calibration using current workflow (potentially also with mask)
1. User runs experiment with sample
1. Visualization computer:
    1. Computes/Queries for:
        1. Dark image
        1. Dark subtracted image
        1. Background image (if it exists)
        1. Dark subtracted background
        1. Background corrected Foreground
        1. Polarization corrected Image
        1. Mask (if not previously available, maybe)
        1. I(Q)
        1. PDF (provided that the composition is in the start)
        1. Puts data into analysis databroker (maybe)
    1. Displays:
        1. Raw image
        1. Polarization corrected image
        1. Mask
        1. I(Q) as a waterfall
        1. PDF as a waterfall
    1. Writes to disk in a user accessible, descriptively named folder/file (potentially multiple places? User gets copy on local drive and beamline archives copy?):
        1. Dark corrected Tiff
        1. Mask in .npy and .msk formats
        1. I(Q) in .chi format
        1. PDF in .gr format
1. User continues to take data, visualization computer continues to display it.
1. Should visualization fail: a) user restarts the analysis script, b) can switch back to old workflow of `save_tiff`, and `save_and_integrate`.
1. User finishes taking data and copies data from visualization computer and/or controls computer.
1. Beamline staff clears analysis folders

### New Schema
1. Users use existing workflow
1. Stronger links between data are created
1. (Maybe allow for the retaking of calibration data?)
1. Maybe new command for alerting the system to a change in the detector (SAXS vs. WAXS/PDF)

### Long Term Beamline Configuration
1. Beamline staff write as much beamline configuration information into the Long Term Beamline Configuration file in ipython_ophyd (which beamstop/beamstop holder are being used, any changes from normal operating procedure, etc.)
1. Software puts metadata from this file into run start documents allowing for rich queries on the beamline status (eg only compare data where the beamline configuration was the same)

**Comment by sbillinge** [comment]
I don't see any releases here.  What is the workflow here?

**Comment by CJ-Wright** [comment]
This is the release for the entire stack. We can put a due date on it and close it just as we would a milestone. The benefit is that this goes across repos so we can deal with all the intra-stack dependencies.

**Comment by sbillinge** [comment]
Quick question @CJ-Wright ....as well as commenting, should we be editing the original comment so that it becomes the release definition?  I do have permission to do that it seems.

**Comment by CJ-Wright** [comment]
Yes, please feel free to edit as you see fit.

**Comment by CJ-Wright** [comment]
@sbillinge In the future (not this release?) we may try to put these documents under a PR into a folder inside the repo? This would mean that we could comment on the release spec/modify it without having to rewrite our comment history. The downside is that it wouldn't be tied as closely to the epic.
