### ISSUE TITLE
Automated shutter plan

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#11]
1. User conducts temperature dependent experiment
2a. User prefers shutter being closed between temperature points to protect sample and detector
  3a. User creates temperature-ramping scan plan with default arguments
  4a. User runs scan plan
  5a. Program keeps shutter closed between temperature points and program opens shutter when collecting data
2b. User prefers shutter being open throughout entire experiment
  3b. User creates temperature-ramping scan plan with descriptive arguments
  4b. User runs scan plan
  5b. Program keeps shutter open during entire experiment

**Comment by CJ-Wright** [comment]
@chiahaoliu I think this is done please reopen if not.
