### ISSUE TITLE
way to bypass calibration in xpdAn

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#121]
It might be nice to have a way to bypass the calibration step in xpdAn (for instance we are re-running all of the data for a beamtime through the pipeline.

Attn:
@sghose

**Comment by sbillinge** [comment]
What is the status of this?

**Comment by CJ-Wright** [comment]
In PR https://github.com/xpdAcq/xpdtools/pull/47

**Comment by CJ-Wright** [comment]
This is done. We can now set a dict setting so as to not run calibration gui.
