### ISSUE TITLE
use hints for saving

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#123]
Currently we have a very bespoke file name template for providing human readable filenames. However, this doesn't fully capture the flexibility of the data. It would be nice if we use the hints interface for tracking the interesting parts of the data. 

## Expected Behavior
Use hints to save reduced data with meaningful filenames

## Current Behavior
Template drives data saving.

## Possible Solution
1. Have `ToEventStream` spit out hints
1. Combine (via chaindb) the raw data stream and the analyzed data stream
1. Create a callback which ingests the combined stream and saves the files

Since `ToEventStream` takes precedence over other forks in the pipeline files will be saved as soon as the data is available.

Note that we should also make this saving node async so we don't wait for the data to be saved to do other things, maybe?

**Comment by sbillinge** [comment]
Not a high priority for us
