### ISSUE TITLE
have swap on global as context manager

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#124]
We've run into issues with the dark settings a couple times. It would be great to have a context manager so we could sandbox certain aspects of the globals.

## Expected Behavior
```python
with glbl.swap('auto_dark', False):
    # runs without auto dark
    xrun(42, 24)
# runs with dark
xrun(0, 0)
```

## Current Behavior
```python
glbl['auto_dark'] = False
# runs without auto dark
xrun(42, 24)
# need to remember this!
glbl['auto_dark'] = True
# runs with dark
xrun(0, 0)
```

## Possible Solution
see `xonsh` env

(this caused a 30 minute call of support)

**Comment by sbillinge** [comment]
yes, this is nice.

I will add to cycle 3 but we will remove if it is too much work.  Is ``xonsh`` already a dependency?

**Comment by CJ-Wright** [comment]
I wasn't planning on using `xonsh` proper, just as an inspiration for `swap` like context manager.

**Comment by CJ-Wright** [comment]
See: https://github.com/xonsh/xonsh/blob/master/xonsh/environ.py
