### ISSUE TITLE
File name format

### ISSUE THREAD

**Issue by jmbai2000** [xpdAcq/mission-control#129]
I think we should change the format of the chi files saved by the streamline. 
1, we should add a reasonable scale factor so that y-column has no numbers less than 1. Since most data processing programs will take the y-column as number of counts, with the too low normalized counts, there will be artificial steps showing in the plot. (see attached plot)  Actually I don’t think the normalization is necessary at all.
2, the texts before the data columns should all start with #, so that the data processing program will ignore them when plot the data. Right now the Jade program cannot read the chi files unless we manually remove the headlines.
3, add some more meaningful information in the headline, such as wavelength and sample-detector distance. Please compare the chi file and the xy file given by Dioptas.   I don’t see why we need to add in every data file these lines  “This file contains integrated powder x-ray diffraction intensities. First column represents two theta values (degrees) and  second column represents intensities and if there is  a third column it represents the error values of intensities.”
4, It is crazy to keep 20 digits in the data columns, in the scientific numerical format, 10 is more than enough.

**Comment by CJ-Wright** [comment]
@jmbai2000 Thank you very much for reporting!

**Comment by CJ-Wright** [comment]
The current `.chi` saving capability is from [scikit-beam](https://github.com/scikit-beam/scikit-beam) which is maintained by the DAMA group. Do you mind if I open an issue at that repo with the problems your raised here?

**Comment by jmbai2000** [comment]
Not at all. Please go ahead.
		
		

		Get Outlook for iOS
	




On Wed, Aug 1, 2018 at 7:40 PM -0400, "Christopher J. Wright" <notifications@github.com> wrote:












The current .chi saving capability is from scikit-beam which is maintained by the DAMA group. Do you mind if I open an issue at that repo with the problems your raised here?

**Comment by sbillinge** [comment]
I will close this issue, as it is now a scikit beam issue.  Thanks for posting that @CJ-Wright 

@jmbai2000 , please follow up with the DAMA group for next steps.

S

**Comment by jmbai2000** [comment]
How to save the data file from the central storage to local disc after the
experiment

From a remote computer, with help of CJ, I can search and save individual
file with the following steps;

1, from shell: conda activate
/home/xf28id2/conda_envs/collection-2018-2.1-XPD
2, ipython
3, In [1]: from databroker import Broker
4, db = Broker.named('xpd')
5,In [3]: hdrs = db(text_search= 'Ceria_std_28')

6, In [4]: hdr1 = list(hdrs)
7,  docs = hdr1[0].documents(fill = True)
8, In [11]: from xpdan.pipelines.save_tiff import raw_source
9, from xpdan.pipelines.save_tiff import save_kwargs
10, In [14]: for nd in docs:
    ...:     raw_source.emit(nd)
    ...:

This will save the 1st tiff file and yml file in the folder ceria_std_28:
saving file at
/home/jmbai/xpdUser/tiff_base/Ceria_std_28/meta/Ceria_std_28_a8f498.yaml
START ANALYSIS ON a8f498f8-9940-4feb-b6b9-c4c13cf8a115
saving file at
/home/jmbai/xpdUser/tiff_base/Ceria_std_28/dark_sub/Ceria_std_28_20180719-111737_a8f498_0001.tiff
FINISH ANALYSIS ON a8f498f8-9940-4feb-b6b9-c4c13cf8a115

I wonder if we can combine 1,2,3,4,8,9 into one command (like
setup_analysis) , and I would like to know how to save multiple files in a
folder with a single command.

Jianming

**Comment by CJ-Wright** [comment]
@jmbai2000 can you please open a new issue for this?

**Comment by jmbai2000** [comment]
yes, I did yesterday. Have you seen it?

**Comment by CJ-Wright** [comment]
Yes, I have, sorry I've been a bit bogged down rn.
