### ISSUE TITLE
REF: stream-friendly function from acquisition

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#13]
Refactor backends of macro/functions currently used in ``xpdacq`` to a stream-friendly pattern. As analysis pipeline will run in another process, we need to avoid the current logic of linking information to ``glbl`` state in the acquisition environment.

Two major functions in ``xpdacq``:
1. ``run_calibration``
2. ``run_mask_builder``

**Comment by CJ-Wright** [comment]
It seems that run_mask builder is not long for this code-base so closing, as `run_calibration` has been refactored.
