### ISSUE TITLE
ENH: slightly better release definitions in mission-control

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/mission-control#14]
@CJ-Wright I am not so happy with the fact the milestone details doesn't support md.  To get around this, and also to make our release definitions somehow more archival, I wonder whether we should have a place in the mission-control repo (or indeed any repo), maybe a directory called "releases" or something, where we put release definitions written in md.  Can we then put a link to the particular release definition in the milesone details page?  I am not sure if this will work, but these release definitions are SO IMPORTANT and having htem all scrambled is a pain.  It would be nice if, when we go to the milestone in GitHub we could click on the link and the definition opens in a new window with the md properly rendered....sthg like that?

**Comment by CJ-Wright** [comment]
Works for me.
I'll try to put something together (although most likely after our soft release/onsite testing this week). Additionally this means that we can put a release template in where we just copy and paste things in.

**Comment by CJ-Wright** [comment]
I'm moving this off this milestone.

**Comment by CJ-Wright** [comment]
@sbillinge Is the current release folder to your liking? If so can you please close this issue?

**Comment by sbillinge** [comment]
yes, to my liking
