### ISSUE TITLE
stuff filterbank attenuation into configuration information

### ISSUE THREAD

**Issue by adelezh** [xpdAcq/mission-control#144]
## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by sbillinge** [comment]
@DanOlds it would be awesome if you could take this.  It is basically a task of periodically measuring attenuations (at different fixed energies) for each filter in a bank, then entering the info into a "long-term" config file on PDF (and XPD).

**Comment by CJ-Wright** [comment]
I put last cycle's factors in, although it will need to be updated when the beam has returned.
