### ISSUE TITLE
Plot of Highest Value vs Independent Variable(s)

### ISSUE THREAD

**Issue by Sasaank** [xpdAcq/mission-control#146]
Use Case:
1. User begins n-dimension scan.
2. Software creates a plot and .csv file.
3. At each change in the independent variable(s), software calculates the maximum value of the pdf per position.
4. Software updates the plot of Highest Value vs Independent Variable(s).
5. Software appends highest value to one column of the .csv and the independent variable(s) to the other column(s).
6. At the end of the scan, software displays finished plot, saves and closes .csv file.

**Comment by sbillinge** [comment]
Plot max value vs index for F(Q) and G(r) and i(q) but also plot a second qoi which is the Q/r value of the max value.

**Comment by CJ-Wright** [comment]
Done here: https://github.com/xpdAcq/xpdAn/blob/master/xpdan/startup/analysis.py#L137
