### ISSUE TITLE
Verbose name of detector object

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#153]
We might need more verbose names for the detector objects, since now both far and near detector are connected simultaneously.  User could trigger the one that's not in the beam easily when they are coding their own plan...

attn: @sghose @dooryhee 

## Expected Behavior
Simple alias will be helpful, like
```
near_det = pe1c
far_det = pe2c
```

## Current Behavior
User can trigger `pe1c` when far detector is in the beam

## Possible solution
Assign alias (approved by the beamline staff) during startup?

**Comment by CJ-Wright** [comment]
@xpdAcq/bls Thoughts?

**Comment by DanOlds** [comment]
I'm not sure what the purpose of this is.  Aren't we able to do this at the
ipython level?

**Comment by chiahaoliu** [comment]
Yes. we are able to do it at ipython level easily. The hope of this discussion is to come up with persistent names (approved by beamline) that will live in the start-up sequence.

**Comment by CJ-Wright** [comment]
I think we can close this, right @DanOlds?

**Comment by DanOlds** [comment]
Super close!
