### ISSUE TITLE
Fast shutter delay

### ISSUE THREAD

**Issue by DanOlds** [xpdAcq/mission-control#154]
The beamlines request an adjustable delay at the start of collecting data for xrun to fully allow time for the fast shutter to open.  This is considered a high priority by the beamline staff, as the issue is corrupting data integrity from in situ measurements on both XPD and PDF.

## Current Behavior

Currently, xrun expects that when a 'shutter open' signal is received, the fast shutter is fully open.  Unfortunately, the epics signal to open the fast shutter is ferried from the network to the hardware of the shutter itself via the EPS system, which is not instantaneous (and in fact, can have a small variable delay).

This has led to the situation where xpdacq seems to believe the fast shutter is open before it actually is, if only by a second.  Unfortunately, this 'closed shutter' data is merged into the full 'light' image that is collected, polluting the data.  I have tested this by measuring single-frame exposures on both beamlines, and found it leads to an effectively blank detector (dark-like image).  

Users would be unaware of this issue in most cases, as the majority of images are composed of multiple exposures.  Several short-exposure (10-5 Hz) in situ measurements over the last month have seen seemingly random-drops in intensity over the course data collection.  It appears to be related to this shutter issue.

## Possible Solution

In the long term, we will seek to modify the fast shutters to accurately report open/closed status.  However, in the interim, a variable delay could be introduced to xrun, which allows time for the shutter to fully open (e.g. glbl['fast_shutter_delay'] = .5).

This would also allow for testing and verification of the future shutter modifications.

**Comment by CJ-Wright** [comment]
We've added a delay time in the most recent release. However, I'll leave this issue open so that we can use it as a reminder to fix this on the hardware side ASAP.

**Comment by CJ-Wright** [comment]
This is implemented and at XPD and PDF the key is `shutter_delay`

**Comment by DanOlds** [comment]
I'm not sure the key 'shutter_delay' is correct.  However, there is an entry for 'shutter_sleep' in the glbl list.  Something seems not correct in the current version of xpdacq on PDF.

**Comment by CJ-Wright** [comment]
Do we still need the delay?

**Comment by CJ-Wright** [comment]
I think this prototype version of this may have had inconsistent names across the beam lines and this repo. They'll be consistent once this is released.
