### ISSUE TITLE
option to bypass visualization pipe

### ISSUE THREAD

**Issue by adelezh** [xpdAcq/mission-control#165]
at xpdAn, we would like to have an option to choose only integrate and save data,  without visualization. This will be very useful when the visualization pipeline fails or when it is too slow.

start_analysis()
start_analysis_noshow()

**Comment by CJ-Wright** [comment]
Thank you for reporting!

The plan is to separate the data processing from the data visualization via ZMQ, that way each can run at whatever rate they can achieve.

**Comment by sbillinge** [comment]
to be clear, we will be rolling this out in the 2019 cycle-1 release
shortly.  It will need to be tested.

The way it will work is that visualization and saving will be in different
processes, each subscribed to the stream through ZMQ, so regardless of
whether you have viz turned on or off, it will not affect saves.  We will
also have analysis pipelines running in the same way, so it will be
possible to have multiple pipelines running if you want, all in separate
processes, all subscribing to the raw stream, and they shouldn't interfere
with each other.

S

**Comment by CJ-Wright** [comment]
I think this is taken care of now, since one can decide not to run the `viz_server`. I'd advise running the viz server on a viz specialized workstation, since if the viz gets slow then the computer can be rebooted without fear.
