### ISSUE TITLE
PDFGETX3 installed incorporated with pipeline at WS-3 28ID-2

### ISSUE THREAD

**Issue by sghose** [xpdAcq/mission-control#169]
We would like to have all the environments and reduction softwares etc.. to be working the exact same way in both WS-2 & WS-3 of 28ID-2. Currently we can not get reduced F(q) and Gr in WS-3.

## Expected Behavior
get Fq & Gr from inline data reduction

## Current Behavior
no pdfgetx3

## Possible Solution
instal pdfgetx3

## Context
WS2 has some GPFS/Network issue. So we are using WS3 for data acquisition and visualization and analysis. But reduction does not provide Fq Gr.
### Priority
Needed now as the users are still using WS3 until the WS2 issue get resolved.

**Comment by CJ-Wright** [comment]
Thank you for reporting!
I will try to get this done today.

**Comment by CJ-Wright** [comment]
This is done now
