### ISSUE TITLE
tseries shutter protocol

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#17]
Generalize the `Tramp`/`Tlist` protocol to `tseries`.

1. User conducts `tseries` experiment
2a. User prefers shutter being closed between time points to protect sample and detector
  3a. User creates time series scan plan with default arguments
  4a. User runs scan plan
  5a. Program keeps shutter closed between time points and program opens shutter when collecting data
2b. User prefers shutter being open throughout entire experiment
  3b. User creates time series scan plan with descriptive arguments
  4b. User runs scan plan
  5b. Program keeps shutter open during entire experiment

**Comment by sbillinge** [comment]
I think this is an important case.  We are maybe overthinking it a bit.  Assign @chiahaoliu for 2018-1, but let's discuss about not making it too complicated.

**Comment by chiahaoliu** [comment]
A more sustainable way to achieve this UC would be PR into ``bluesky`` so that the bluesky ``count`` takes ``per_step`` and we can use a similar pattern in ``Tlist`` and ``Tramp``.

**Comment by CJ-Wright** [comment]
I think this is in.
