### ISSUE TITLE
PDFs not generated at 28-ID-1

### ISSUE THREAD

**Issue by DanOlds** [xpdAcq/mission-control#188]
The reduction pipeline doesn't seem to think PDFgetX3 is installed, and thus, no PDFs are being generated via the autoreduction on 28-ID-1.  

We have noticed this occurs frequently when an update to bluesky or xpdacq is pushed out.

**Comment by CJ-Wright** [comment]
This happens when new environments are installed, since PDFgetx3 is not a conda package and is currently installed from source by hand. I can run the install now but this is going to keep happening until a private conda package for PDFgetx3 is created.

**Comment by CJ-Wright** [comment]
cc @mrakitin

**Comment by mrakitin** [comment]
@CJ-Wright, please proceed with the manual installation as figuring out how to handle it automatically may take time.

**Comment by CJ-Wright** [comment]
Finished for ws2 (will do ws3 and ws1 a little later)
