### ISSUE TITLE
xpdAcq supports 2-detector positions

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/mission-control#201]
Support 2 detector position scans in xpdAcq.  Not sure if we just need new built-in scanplans or sthg else

## Expected Behavior
tbd.  Simply speaking it could be interleaved runs (near,far,near,far) etc. but it could be other logic.  Need UCs from instrument scientists

**Comment by st3107** [comment]
some design:

1. Xpdacq: inject information of "xraydectector: [det1, det2, ...]" to sepcify the names of the xray detector names that will be processed by PDFstream. PDFstream read the names to know what detectors are there.
2. PDFstream: find the calibration data when the images come according to the detector names and the motor position. When it searches the value, it should have some tolerance, like x = 19.9999 can use the calibration from x = 20.0
3. PDFstream: dump the calibraiton into the database with the detector name and the motor position.
4. Xpdacq: when a run starts, load the calibraiton data from the database accordng to the motor position and the dector name. Here, in the start document, there should be a mapping from the detector names and motor positions to the calibration metedata.

**Comment by st3107** [comment]
```
def xpdacq_count(dets, indeps, calibration_md):

```
