### ISSUE TITLE
DEV: add dexela and motors to the profile_collection D-hutch

### ISSUE THREAD

**Issue by st3107** [xpdAcq/mission-control#205]
Update the profile collections of D_hutch.

## Expected Behavior

We need to make the profile collection working for D-hutch. Users can run xpdAcq and PDFstream for D-hutch devices.

## Possible Solution

Add dexela.py and motors.py to the profile_collection.

Determine where the tiffs should be saved.

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by sbillinge** [comment]
thanks @st3107. please can you assess how much of your time this would take?  rough estimate in days assuming others have provided all info you need.  Thx.

**Comment by st3107** [comment]
I will do it today.

**Comment by st3107** [comment]
Hi @sbillinge . This issue can be closed. The motors and detectors have already been added in the profile collection.

**Comment by sbillinge** [comment]
thanks @st3107
