### ISSUE TITLE
fix autodark so that it can be turned on and off

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/mission-control#225]
Autodark global never teste

## Expected Behavior

Can collect lights even if darks are turned off

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by st3107** [comment]
This global variable is deprecated together with the old dark protocol. I move the functionality to the dark preprocessor instances.

**Comment by st3107** [comment]
This global variable is deprecated together with the old dark protocol. I move the functionality to the dark preprocessor instances.
