### ISSUE TITLE
Beamline config docs

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#43]
need some docs for long term beamline config (or put them into `For Beamline Staff`)

**Comment by sbillinge** [comment]
Problem is that 
1) Beamline staff haven't created the long-term config file
2) It needs to be part of the beamline-staff workflow e.g, part of the start_beamtime workflow (at the very least)

1) will be addressed by documentation and training.
2) will need
   a) training
   b) other incentives!   
        i) capture name or initials of person doing start_beamtime
        ii) print beamline config during start_beamtime.  Ask "is this the current beamline configuration?" and require staff to type 'yes' or 'no' to continue
        iii) if 'no', config file is opened in a text editor and saved to the right place on ctl-s.  After saving we should loop back to (ii)
        iv) if 'yes', save statement, 'beamline config validated by <initials> on <datetime>' into config file.

**Comment by sbillinge** [comment]
@dooryhee suggests to save more of the machine PV's as a first step.   

We should discuss precisely which we will save.  This gives a lot of the machine config out of the box and is more robust than a config file that can easily go out of date!

@sbillinge suggests to save a wide-angle webcam image of the hutch as a piece of metadata.   What we need is a PV for this camera.  This could go to cycle 2 if it is too difficult.

@dooryhee wants a user-editable beamline-config file that users can fill in info about their setup (or instrument scientists if they are helping users) but it is accessible to users.

**Comment by CJ-Wright** [comment]
1. We can most likely do that, but that still doesn't capture all the info we need (I don't think we have a PV for the beamstop holder).
2. The only issue with the camera is that it isn't machine readable, so it may be difficult to infer some of the configurational data.
3. That should be doable.
