### ISSUE TITLE
Flexible Folder tag

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#44]
Currently we have a sacred key in the metadata `folder_tag` which when given tells the analysis software to put the data into a directory under the sample directory. This could be more flexible allowing multiple nested directories.

## Expected Behavior
User specifies `folder_tag_list` as a list of keys in the metadata (or not in the metadata, we will leave blank).
Analysis software puts the files written out into a directory `.../value_for_key_0/value_for_key_1/...`

## Current Behavior
Currently there is only one level of nesting

Attn: @sbanerjee23

**Comment by sbillinge** [comment]
I would rather put resources into making databroker more effective than making it easier to use file folders.  This is a general thought.

However, I think that tagging is actually a great way to make databroker more effective for users....so this may be a subtle way of getting what we want without the users realizing!

Or to put it in a less adversarial way, user tagging of datasets is a great way of starting the bundling process regardless of whether downstream we are using file-folders or databroker.

**Comment by sbillinge** [comment]
Suggest that default behavior doesn't change from current behavior....i.e., sample-name head-directory.

new default behavior will be that specified keys in the tag-list are appended.

optional behavior for users is to overwrite the list, so that the head-directory is no longer sample-name

**Comment by CJ-Wright** [comment]
Closing as this went in in a PR. Thank you very much @eaculb
