### ISSUE TITLE
DOC: make ``xpdusers`` group more visible

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#46]
It would be great to promote it a bit more so that we have a centralized place for the questions at the first place.

**Comment by sbillinge** [comment]
Can we discuss the vision for a new start_beamtime() sequence that gives a nice clean desktop with documentation pre-opened?

**Comment by CJ-Wright** [comment]
See #50

**Comment by sbillinge** [comment]
closing as it will be fixed in #50
