### ISSUE TITLE
ENH: Turn masks off for non-setup scans

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#47]
Users may not want to mask things.

## Expected Behavior
User specifies that a scan is not to be masked (discussed below).
The pipeline does not create a mask

## Current Behavior
Unless the scan is a setup scan then the mask is created.

## Possible Solution
Have a sacred key in the metadata which designates if the data should be masked.
Have the pipeline understand this key.

Note that this approach is a bit problematic (although very doable). The problem here is that we are now loading up our metadata about the experiment with metadata about how we want our _analysis_ to run. This has some nasty side effects:
1. It blends the two kinds of metadata.
1. It writes into stone a very mutable quantity (eg if you wanted the mask run could change on your mood, and available time)
1. It cause problems down the road with analysis (if you wanted to re-run your analysis you would have to override this to get a mask)

These nasty side effects hint that we may need a different modality for interacting/interfacing the user, raw data, and pipeline. @xpdAcq/core Thoughts?

## Context
The masking is too slow?
Azimuthal averaging doesn't apply to all samples? (although if that is true then most of the pipeline is not applicable to the data)

I could use some help here @xpdAcq/bls with the contex.

**Comment by sbillinge** [comment]
is there a quick and ugly workaround?  A full fix requires us revisit some low-down design decision about the pipeline and I want more feedback from users about how they are using the pipeline before we go there.

**Comment by sbillinge** [comment]
I agree that mixing the metadata is maybe bad but it is forced on us by
some inflexibility in the framework. This inflexibility may be good or bad,
but we should think a bit about how the framework will be used and the main
design goals of the framework before doing anything here.

The main reason not to mask is time.

A workaround could be a logic where, as with darks, the user sets a
mask-window and a new mask is only generated if there is no "good" mask
available. This gives the user flexibility to automask on every frame (by
setting a short window) or rarely (by setting a long window).
