### ISSUE TITLE
ENH: single command for acq, an, and proxy

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#48]
We need to provide a single command to start acq, an, and the proxy so that the users/BLS don't run into issues with the proxy and other things not being started in the right order.

## Expected Behavior
One command to rule them all.

## Current Behavior
Currently we have three commands which requires an exact sequence of calls.

## Possible Solution
Bash terminal wizardry (which I am not currently aware of).
I think there may be more elegant solutions.

## Context
If this gets messed up currently the pipeline grinds to a halt.

### Priority
Highest (Due yesterday)

**Comment by sbillinge** [comment]
👍

**Comment by CJ-Wright** [comment]
This is getting rolled into the whole login-logout system I'll leave it open for now.

**Comment by sbillinge** [comment]
superceded by #50 

Closing this baby
