### ISSUE TITLE
REF: interactive step in run_calibration should happen in the same process as the process it's executed 

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#51]
It might be less intuitive to execute ``run_calibration`` inside the collection terminal but interact with ``pyFAI`` in another analysis terminal

## Expected Behavior
execution of ``run_calibration`` and the interaction with ``pyFAI`` should happen in the same terminal.

## Current Behavior
user has to find analysis terminal and finish the calibration step after ring selection with ``pyFAI`` gui

## Possible Solution
revert the old behavior, ``run_calibration`` happens in the same process as ``xpdAcq``

**Comment by sbillinge** [comment]
This sounds like a small thing but is currently very confusing and non
intuitive so I would love it fixed

**Comment by CJ-Wright** [comment]
We could do this. We could subscribe to xrun the pipeline (which will cause it to block the main terminal) and then unsubscribe it inside the `run_calibration` function.

**Comment by sbillinge** [comment]
I would like to request that we add this to 18–1 milestone

**Comment by CJ-Wright** [comment]
Sure, feel free to add it.

**Comment by CJ-Wright** [comment]
Also we need to remove the ZMQ callbacks when running the calibration so that it doesn't push data to ZMQ (which will try to do the calibration itself currently)

**Comment by sbillinge** [comment]
after discussion with @CJ-Wright let's just have `run_calibration()` write a print statement that tells users that control has been handed to the analysis terminal and to click there after selecting rings.

This is much less work but should solve the problem that the current workflow is not intuitive.

Also in this issue:
1) fix calibration documentation for current workflow
2) make a link from QuickStart to the full calibration instructions

With this lightening of the load, let's put this to 2018-1
