### ISSUE TITLE
ENH: wrap bluesky RE print statement when scan is interrupted

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/mission-control#52]
When doing ``ctrl+c`` to interrupt the scan, native ``bluesky`` print statement would instruct user to stop the scan by doing ``RE.stop(), RE.abort()`` etc. 

But the run engine instance in ``xpdacq`` is called ``xrun``, so user actually has to do ``xrun.stop()``  to stop the scan.

## Expected Behavior
proper print statement with ``RE`` replaced by ``xrun``

## Possible Solution
PR into ``bluesky``

attn: @danielballan

**Comment by danielballan** [comment]
I would factor this as a PR that makes the `PAUSE_STR` a configurable attribute of `RunEngine`.

**Comment by chiahaoliu** [comment]
would make ``RunEngine`` class take an optional arg ``name`` a reasonable approach(default to ``RE``)?

So that we can have something like ``"{}.abourt".format(name)`` in the ``PAUSE_MSG``.

**Comment by danielballan** [comment]
I think it's likely that people might want to customize the pause message even more heavily (or omit it altogether) so I think it make sense to provide this more aggressive hook.

Also, the idea of a Python variable having a name is ill-defined because I can do:

```
RE1 = RE2 = RunEngine({})
```

and now what's the name?

**Comment by sbillinge** [comment]
Let's shoot for 2018-1 but this can slide if it is more work than we think when we dig into Bluesky

**Comment by sbillinge** [comment]
Let's discuss about 2018 cycle 1 if this is too mcuh work.

**Comment by chiahaoliu** [comment]
This issue has been addressed in ``xpdAcq`` issue #466 and it's closed via PR #467.

Close this issue.
