### ISSUE TITLE
DOC: tell BLS how to change the pipeline config

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#55]
Beamline scientists should be able to change the parameters of the pipeline config.
This is currently possible, it just needs a bit more docs (although [these are the parameters](http://xpdacq.github.io/xpdAn/xpdan.pipelines.html#xpdan.pipelines.main.conf_main_pipeline))

**Comment by sbillinge** [comment]
This is a new UC so we should discuss before offering this.  Currently
there is no
#) User/BLS modifies the pipeline config
in any of our released UCs.

I would rather develop the pipeline first and return to this.  Reasonable
requests for different preconfigured pipelines could be a way forward.

**Comment by CJ-Wright** [comment]
The context for this was changing the PDF producing parameters (Qmax, rpoly, etc.)

**Comment by sbillinge** [comment]
This can be done in xpdgui which is the normal workflow, though I see why
this might be useful in the pipeline

**Comment by sbillinge** [comment]
after conversation with @CJ-Wright , We think limited pipeline configurability could go into release 2018-1.  This would support the following UC:

1. User wants different Qmax, rpoly, Qmaxinst, Qmin for the live feed (note that these can all be changed later in XPDsuite in any case)
1. User asks beamline scientist (BLS) to change the config
1. BLS exits the analysis ipython session
1. BLS edits 999-load.py in the analysis profile by updating `conf_main_pipeline()` function <DANGER - editing 999-load.py can cause everything to break....don't let users do it, and do it at your own risk>
1. BLS restarts the analysis pipeline
1. BLS returns control to the users.

NOTE: at the end of the beamtime, it is essential that BLS returns the 999-load.py to its original state for the next user.

**Comment by CJ-Wright** [comment]
I think this could be done more simply.
1. run `setup_analysis`
1. Change configuration file
1. run `start_analysis()` to kick off the analysis server
1. Don't like analysis configuration
1. kill analysis server
1. change config file
1. run `start_analysis()` again
