### ISSUE TITLE
BUG: users save data with the old workflow

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#58]
It seems that there are some bugs in the code which force the users to use the old saving workflow.
There may be a couple of sources for this:
1. Pipeline crashes due to composition missing. It seems that composition is more optional than we thought, so we should put a filter to check if the composition information exists.

**Comment by sbillinge** [comment]
My suggestion is a quick fix for this bug for mid-cycle release using if-statements and stopping at i(q) if there is not composition.

However, we should make an issue for a later release where the exceptions are passed down but the pipeline doesn't break.

**Comment by CJ-Wright** [comment]
I think this has been fixed in the new pipeline.
