### ISSUE TITLE
ENH: xpdAcq support for the XPD robot

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#59]
It would be good to support the XPD robot with xpdAcq.

## Expected Behavior
1. User loads samples into cartridges (which hold one sample each) and notes which sample was loaded into which cartridge
1. User loads cartridges into a sample magazine (the box)
1. User run command at XPD to run the robot on all the cartridges.
1. Robot puts samples into place and takes shots according to the inner loop scan plan (this is a sticking point, how do we know what scan to run?)

## Current Behavior
Robot is not supported by xpdAcq.

## Context
The robot will help groups with many samples to take data faster, with more confidence, and less sleepy users.

Attn: @dooryhee

**Comment by CJ-Wright** [comment]
Here are some possible sticking points:
1. Associating samples with cartridges:
   1. How does the user associate the sample data with the cartridge? 
   1. Can we have them enter the cartridge name into the sample spreadsheet?
1. Associating sample data during scan: 
   1. How does the software put the sample data into the start? 
   1. Do we get a start document when the robot starts moving? If so then we may run into some issues. 
   1. If not can we have the robot read off the cartridge barcode and then we do the lookup to the sample info before the data is taken?
   1. What kind of data do we get back from the robot in terms of the barcode reading?
1. Running the scan:
   1. How do we run data collection with the robot? 
   1. Do all the samples get the same plan? 
   1. Can we run this with adaptive scans? 
   1. How do we not burn the detector if the samples are very different?

**Comment by CJ-Wright** [comment]
From @dooryhee:
>I suggest we sit at the beamline during a beam-off day and go through a dummy run using the robot and the existing Bluesky robot class, to refine workflow and identify problems. 
>One scenario is:
>- 00 user enters cartridge name and location in the spreadsheet
>- 10 list = all samples in the magazine (as per spreadsheet)
>- 20 count_time = 0.1sec
>- 30 robot runs all samples in list for count_time
>- 40 robot returns a new list of all samples/datasets whose max count is < 1/10 detector saturation (i.e. 6,000)
>- 50 list = new_list
>- 60 count_time = count_time x 10
>- 70 if list <> empty then go to 30

**Comment by CJ-Wright** [comment]
From @dooryhee
>But the robot loop is way slower that the count/acquisition time. Therefore, it is better to swap inner loop and outer loop, i.e. have multiple counts for each robot pick-up.

**Comment by CJ-Wright** [comment]
Proposed robot access via xrun:
```python
xrun(None, 1, robot=True)  # run a robot scan on all samples, for each sample run scan 1

xrun([3, 4, 5], 1, robot=True)  # as above but only samples 3, 4, and 5 are run

xrun(3, 1, robot=True)  # as above but only sample 3 is run

xrun(None, [1, 2], robot=True)  # all samples run, each sample is run with scan 1 and 2 (in separate headers, sequentially (load sample 1, run scan 1, run scan 2, load sample 2, ...))

xrun([3, 4], [bluesky_plan_1(det), bluesky_plan_2(det)], robot=True)  # run all samples with bluesky plans

xrun.md['robot'] = True  # This will fail on xrun call, no global robot md (to protect from unintended robot use)
```

**Comment by CJ-Wright** [comment]
Note that the above syntax also supports multiple scans without the robot:
```python
xrun(1, [1, 2])  # run scans 1 and 2 on sample 1
```
However multi sample runs without the robot flag will cause an error.

**Comment by CJ-Wright** [comment]
@dooryhee what does the robot do if the magazine is only partially filled with samples?

**Comment by CJ-Wright** [comment]
@dooryhee is it possible to have the vendor expose the robot's inventory of the magazine through the epics layer?

**Comment by CJ-Wright** [comment]
I'm going to break up this issue into a bunch of smaller issues so we can deliver the robot functionality without having an all-or-nothing attitude toward things. As such, I'm going to close this issue since rudimentary robot support has gone into xpdAcq.

**Comment by dooryhee** [comment]
We'll fire up the robot on Thu. 5/10. Then robot will be available for xpdAcq testing.
