### ISSUE TITLE
ENH: 2D scan QOI

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#68]
From @sbanerjee23:
motor x by motor y with intensities:
1. Intensity of Tallest peak in I(Q)
1. Position of Tallest peak in I(Q)
1. Position of Tallest peak in G(r)

**Comment by sbillinge** [comment]
closed by #146

**Comment by CJ-Wright** [comment]
Done here: https://github.com/xpdAcq/xpdAn/blob/master/xpdan/startup/analysis.py#L137
