### ISSUE TITLE
Have a workflow about how release notes make it into the documentation

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/mission-control#76]
make sure users (and managers) can (a) see the current release (b) quickly see what has changed from the previous release.  This is most important for user-facing software

## Expected Behavior
Every new release includes either automated or manual but following a prescribed protocol way of doing this.

## Current Behavior
some changes are there, others are not.  Just needs to be organized/formalized

## Possible Solution
release checklist?

## Steps to Reproduce (for bugs)

1.
2.
3.

**Comment by CJ-Wright** [comment]
Rever has a tool for this. The basic idea is that we keep a [`news` directory](https://github.com/ergs/rever/tree/master/news). Every time we put in some code this directory gets a new file added. When it comes time to release rever will put all the changes into a Changelog for us.

**Comment by CJ-Wright** [comment]
For example xonsh https://github.com/xonsh/xonsh/blob/master/news/alias-command.rst

**Comment by CJ-Wright** [comment]
I think we also need a link between the changelog rst file and something in the webdocs
