### ISSUE TITLE
ENH: No masking

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#78]
Sometimes users *really* just want no masking.

## Expected Behavior
User stops analysis server, changes config and restarts server (this time without masking).

## Current Behavior
This is process is not documented.

## Possible Solution
Document how to stop analysis server, change config, and restart server.

**Comment by sbillinge** [comment]
Support 2 UCs:
1. autogenerate a mask on the first dataset in a scan, then keep the mask throughout the rest of the scan
2. turn off automasking altogether, 
3. as (2) but allow a user to load a manual mask generated by Fit2D or something else.

Desired default behavior for xpdAcq:
for all tramp and Tseries etc., desired default behavior is (1).

**Comment by CJ-Wright** [comment]
I think this really boils down to docs on how to start the analysis with a new instance of the analysis callback (in the currently installed version) or how to modify the pipeline and restart the analysis.
I will add these docs soon.

**Comment by dooryhee** [comment]
Are Simon's 2 UCs part of the new release? and in xpdAcq documentation?
