### ISSUE TITLE
Long Term Beamline Configuration

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#8]
1. Beamline staff write as much beamline configuration information into the Long Term Beamline Configuration file in ipython_ophyd (which beamstop/beamstop holder are being used, any changes from normal operating procedure, etc.)
1. Software puts metadata from this file into run start documents allowing for rich queries on the beamline status (eg only compare data where the beamline configuration was the same)

**Comment by chiahaoliu** [comment]
Finished all the issue tagged in this epic. Close epic.
