### ISSUE TITLE
Template configuration information in docs

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/mission-control#96]
It would be great to template some configuration information in the docs (env names for instance).

**Comment by CJ-Wright** [comment]
We need this ASAP

**Comment by chiahaoliu** [comment]
This thread might be helpful?

[How do I output a config value in a Sphinx .rst file?](https://stackoverflow.com/questions/10030149/how-do-i-output-a-config-value-in-a-sphinx-rst-file/10042061#10042061)

**Comment by CJ-Wright** [comment]
I wonder if that allows full dict addressing.

**Comment by chiahaoliu** [comment]
Yeah, that should be the case. I just checked the [official doc](http://www.sphinx-doc.org/en/stable/config.html#confval-rst_epilog)

**Comment by CJ-Wright** [comment]
I think that is at the end of files though. My plan was to maybe use a jinja2 formatter to run through all the files and fill from some global context dict before the make finishes.

**Comment by chiahaoliu** [comment]
Yeah, that's how I understood from the doc (but not tested yet).

``jinja2`` seems a good and elegant solution too. We can see which one works better.
